Added support to set extra sidecars and extra role permissions.
containeroo/helm-charts pull request #9
Opened 2022-07-26 20:31 UTC by killmeplz

This PR provides support for using operator service account to get IPs from other Kubernetes objects, such as services or Istio gateways.
WDYT?

2022-07-27 18:07 UTC, rxbn commented
Hi @killmeplz 

Thanks for your contribution! We will have a look and merge your PR ASAP :)

2022-08-03 09:44 UTC, rxbn requested changes
See review comments.

2022-08-03 09:44 UTC, rxbn commented on charts/cloudflare-operator/Chart.yaml
> +version: 0.3.4
```suggestion
version: 0.3.5
```

2022-08-03 09:44 UTC, rxbn commented on charts/cloudflare-operator/README.md
> +
This entire part should be in the cloudflare-operator documentation. Please remove it here and create a PR in contatineroo/cloudflare-operator repository.

2022-10-07 15:46 UTC, rxbn approved these changes
LGTM

2022-10-07 15:47 UTC, rxbn commented
@gi8lino Please have a look as well

@killmeplz Sorry for the delay. Changes look good to me. As soon as @gi8lino approves, I will merge!

2022-10-07 16:15 UTC, gi8lino approved these changes
LGTM

2022-10-07 16:15 UTC, merged